### PR TITLE
style: fix the typo in sort_item.go

### PR DESCRIPTION
**Pull request by Chenxulin97**
### What problem does this PR solve?

Correct the spelling in sort_item.go

# Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by shilinlee** [comment]
Please check the CONTRIBUTION_CN.md in this project.

**Comment by Chenxulin97** [comment]
> Please check the CONTRIBUTION_CN.md in this project.

thanx I will modify it and commit again

**Review by Shoothzj — APPROVED** [review]

**Comment by xiangyu5632** [comment]
请修改一下PR的描述

**Comment by Chenxulin97** [comment]
> 请修改一下PR的描述 在这部分 _What problem does this PR solve?_ 下面描述清楚问题，比如解决代码中单词拼写错误。**当前PR需要填写，没有issue也可以填写** 在这部分 _What is changed and how it works?_ 下面填写如何修改的思路，本PR可以不填，因为就是拼写错误改正而已。没有内容就把这部分删除。 在这部分 _How Has This Been Tested?_ 下面，如果写了测试用例，这里可以写一下用例名称，没有就不填，该部分删除。

已经修改了 感谢：）

**Review by shilinlee — APPROVED** [review]

**Review by xiangyu5632 — APPROVED** [review]

**Pull request merged**
