### PR TITLE
fix: ts-cli output corrupted

### LINKED ISSUE #519: ts-cli commnad line text often corrupt when moving the caret in a histroy command
### Describe the bug（Bug 描述）

We often need to use/edit a history command, but in 'ts-cli', the command line text often corrupt when moving the caret.
I've never seen this from other applications, so I think it is a bug of 'ts-cli'.

### To Reproduce（Bug 复现步骤）

1. start `ts-cli` and execute some commands
2. using the UP/DOWN keys to select a history command.
3. using the LEFT/RIGHT keys to move the caret, note to **keep the key pressed**.
4. the command line text corrupt like below, and user is forced to reenter the full command.
```shell
> insert cpu,host=server-01,region=south-cn disk=11,memory=12,network=13
ERR: {"error":"partial write: field type conflict: input field \"network\" on measurement \"cpu\" is type float, already exists as type integer dropped=1"}

> > > > > > > > > > > > > > > insert cpu,host=server-01,region=south-cn disk=11,memory=12,netwo?[D?[Drk=13
ERR: {"error":"partial write: field type conflict: input field \"memory\" on measurement \"cpu\" is type float, already exists as type integer dropped=0"}

> > > > insert cpu,host=server-01,region=south-cn disk=11,memory=12,netwo?[D?[Drk=13
ERR: {"error":"partial write: field type conflict: input field \"memory\" on measurement \"cpu\" is type float, already exists as type integer dropped=0"}
```

### Expected behavior（期望结果）

_No response_

### Screenshots（屏幕截图）

_No response_

### Logs（完整的错误日志）

_No response_

### Additional context（其他的一些补充内容）

_No response_

### PR DESCRIPTION
**Pull request by StepY1aoZz**
### What problem does this PR solve?

fix #519 

### What is changed and how it works?
Fixed issues in my own `go-prompt`  fork where unwanted control characters may be output to screen and part of output cannot be erased from screen. For more details, please see my comment in #519 and https://github.com/StepY1aoZz/go-prompt/pull/1 

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by xiangyu5632** [comment]
tkx @StepY1aoZz

**Review by xiangyu5632 — APPROVED** [review]

**Comment by shoothzj** [comment]
Could you please contribute the changes to https://github.com/c-bata/go-prompt? Depends on personal bug fix fork is unhealthy for a project.

**Comment by xuthus5** [comment]
It should be forked to the opengemini organization for self-maintenance, origin repo has been archived.

**Comment by StepY1aoZz** [comment]
I totally agree that fix this bug in my own fork is not a good choice, but as I mentioned in the corresponding issue #519 and @xuthus5 said, I'm not expecting any contribution could be made to the archived repo `c-bata/go-prompt`. If the openGemini organization wants to maintain an own fork, I am very happy to offer any assistance there.

**Pull request merged**
