### PR TITLE
Fixed terminal not restored after quit issue

### PR DESCRIPTION
**Pull request by nanjj**
### What problem does this PR solve?

Issue Number: ref [c-bata/go-prompt#228]
### What is changed and how it works?
The patch workaround issue [c-bata/go-prompt#228], make the terminal running ts-cli works correctly after quit, exit, ControlC or ControlD.

### How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Run ts-cli on linux, end with exit or quit, watch the terminal normal or not 
- [ ] Run ts-cli on linux, end with Ctrl+c or Ctrl + d, watch the terminal is normal or not

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by xiangyu5632** [comment]
pls alert the commit message follow the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/)

**Comment by nanjj** [comment]
> pls alert the commit message following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) anyway， someone's feedback has the same problem with Linux， and can you also fix issue #519?

1. Done the conventional message,
2. issue #519 I can not reproduce the issue under tmux.

**Comment by xiangyu5632** [comment]
> > pls alert the commit message following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) anyway， someone's feedback has the same problem with Linux， and can you also fix issue #519?
> 
> 1. Done the conventional message,

problem also exits
you can use the following command to commit again
```
git commit -s -m "chore: xxx"

or

git commit --amend
```
commit message needs to add a "chore" or "fix"

**Comment by nanjj** [comment]
> > > pls alert the commit message following the [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) anyway， someone's feedback has the same problem with Linux， and can you also fix issue #519?
> > 
> > 
> > 
> > 1. Done the conventional message,
> 
> problem also exits you can use the following command to commit again
> 
> ```
> git commit -s -m "chore: xxx"
> 
> or
> 
> git commit --amend
> ```
> 
> commit message needs to add a "chore" or "fix" ahead

done

**Review by xiangyu5632 — APPROVED** [review]

**Pull request merged**
